### ISSUE TITLE
Tutorial : virtualbox shared map drag and drop

### ISSUE THREAD

**Issue by arcolinuxz** [arcolinux/To-do-list#6]
Figure out how this works

**Comment by darknetmatrix** [comment]
Is it not the case that the guest must be windows in this case?

**Comment by arcolinuxz** [comment]
Good call - but hopefully not

**Comment by darknetmatrix** [comment]
Here it don't work -> Linux to Linux

**Comment by arcolinuxz** [comment]
works now
there is an alias for it
